server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grandmasfood
    username: root
    password: Sebitas2515
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html